// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCInML6yAyrA2MCxnyZ1ncZN0s0aMznK2k',
    appId: '1:241430276628:web:be432d4b3915bf96a75501',
    messagingSenderId: '241430276628',
    projectId: 'fitnesapp-6cfd4',
    authDomain: 'fitnesapp-6cfd4.firebaseapp.com',
    storageBucket: 'fitnesapp-6cfd4.firebasestorage.app',
    measurementId: 'G-0Q3KC50EZQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAQehf1mNWxMEdbXWkWdrtaciSFkJO8p0Q',
    appId: '1:241430276628:android:3ca080e60f458489a75501',
    messagingSenderId: '241430276628',
    projectId: 'fitnesapp-6cfd4',
    storageBucket: 'fitnesapp-6cfd4.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAT-hWTeC4YJMEYj8rHQM3iLyzC1mW7Hjw',
    appId: '1:241430276628:ios:9a0eec662498fba7a75501',
    messagingSenderId: '241430276628',
    projectId: 'fitnesapp-6cfd4',
    storageBucket: 'fitnesapp-6cfd4.firebasestorage.app',
    iosClientId: '241430276628-46eusnosmoojlme9jboarqlndpbihfsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAT-hWTeC4YJMEYj8rHQM3iLyzC1mW7Hjw',
    appId: '1:241430276628:ios:9a0eec662498fba7a75501',
    messagingSenderId: '241430276628',
    projectId: 'fitnesapp-6cfd4',
    storageBucket: 'fitnesapp-6cfd4.firebasestorage.app',
    iosClientId: '241430276628-46eusnosmoojlme9jboarqlndpbihfsr.apps.googleusercontent.com',
    iosBundleId: 'com.example.fitnessApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCInML6yAyrA2MCxnyZ1ncZN0s0aMznK2k',
    appId: '1:241430276628:web:7e1393ffb5f8f348a75501',
    messagingSenderId: '241430276628',
    projectId: 'fitnesapp-6cfd4',
    authDomain: 'fitnesapp-6cfd4.firebaseapp.com',
    storageBucket: 'fitnesapp-6cfd4.firebasestorage.app',
    measurementId: 'G-85W93L3WP2',
  );
}
