name: fitness_app
description: "A new Flutter project."
publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  firebase_core: ^4.9.0
  firebase_auth: ^6.5.1
  cloud_firestore: ^6.4.1

  google_sign_in: ^6.3.0
  sign_in_with_apple: ^8.0.0

  shared_preferences: ^2.0.15
  intl: ^0.20.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/foods/
    - assets/images/muscles/
    - assets/images/workouts/
    - assets/images/recipes/
    - assets/images/recipes/breakfast/
    - assets/images/recipes/lunch/
    - assets/images/recipes/dinner/
    - assets/images/recipes/snacks/
    - assets/images/recipes/drinks/
    - assets/images/recipes/desserts/
    - assets/images/recipes/starters/

dependency_overrides:
  async: ^2.13.0
  fake_async: ^1.3.3
  leak_tracker: ^10.0.9
  material_color_utilities: ^0.12.0
  vm_service: ^15.0.0